name: Build and Deploy to ECR

on:
  push:
    branches: [ deploy ]
    paths:
      - 'backend/**'

# MANDATORY for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. AUTHENTICATE WITH AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      # 2. LOGIN TO ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. SET UP DOCKER (QEMU + BUILDX)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. BUILD AND PUSH
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/arm64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/playground/image-captioner-mini:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5. UPDATE LAMBDA
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name image-captioner-mini \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/playground/image-captioner-mini:latest